from __future__ import annotations

TEMPLATE = '''\
"""
{name} — Anime Watch Provider Plugin
======================================
Generated by: python -m anime_watch plugin new {slug}

To install:
  cp {slug}.py ~/.config/anime-watch/providers/
  # or just run: python -m anime_watch plugin install {slug}.py
"""

from __future__ import annotations
import re
from typing import Optional

import requests
from bs4 import BeautifulSoup

from anime_watch.providers.base import BaseProvider
from anime_watch.models import SearchResult, Episode, StreamSource, MediaResult
from anime_watch.core import SESSION, SCRAPE_TIMEOUT


class {class_name}(BaseProvider):
    # ── Metadata ────────────────────────────────────────────────────
    name = "{name}"
    slug = "{slug}"
    url = "{url}"
    category = "{category}"

    # ── Search ──────────────────────────────────────────────────────
    def search(self, query: str) -> list[SearchResult]:
        \"\"\"Search for anime/movies matching `query`.

        Returns a list of SearchResult. Each result points to a series
        or movie page, NOT an individual episode.
        Return an empty list on failure.
        \"\"\"
        results: list[SearchResult] = []
        try:
            resp = SESSION.get(
                f"{{self.url}}/search",
                params={{"q": query}},
                timeout=SCRAPE_TIMEOUT,
            )
            if resp.status_code != 200:
                return results
            soup = BeautifulSoup(resp.text, "lxml")
            # ── TODO: parse search results from HTML ──────────────
            # for item in soup.select(...):
            #     title = ...
            #     link = ...
            #     image = ...
            #     results.append(SearchResult(
            #         title=title,
            #         url=link,
            #         site_name=self.name,
            #         image=image or "",
            #     ))
        except requests.RequestException:
            pass
        return results

    # ── Episodes ────────────────────────────────────────────────────
    def get_episodes(self, result: SearchResult) -> list[Episode]:
        \"\"\"Fetch the episode list for a search result.

        `result` is one of the SearchResult objects returned by
        `search()`.  Return a list of Episode objects.
        \"\"\"
        episodes: list[Episode] = []
        try:
            resp = SESSION.get(
                result.url,
                timeout=SCRAPE_TIMEOUT,
            )
            if resp.status_code != 200:
                return episodes
            soup = BeautifulSoup(resp.text, "lxml")
            # ── TODO: parse episode list from HTML ────────────────
            # for ep in soup.select(...):
            #     num = ...
            #     title = ...
            #     episodes.append(Episode(
            #         title=title,
            #         url=result.url,
            #         number=str(num),
            #         site_name=self.name,
            #         anime_name=result.title,
            #         data={{...}},
            #     ))
        except requests.RequestException:
            pass
        return episodes

    # ── Stream ──────────────────────────────────────────────────────
    def extract_stream(
        self,
        episode: Episode,
        audio_pref: str = "sub",
        quality_pref: str = "best",
    ) -> Optional[StreamSource]:
        \"\"\"Extract a playable stream URL for an episode.

        Return a StreamSource with the video URL, or None if
        extraction fails.
        \"\"\"
        try:
            resp = SESSION.get(
                episode.url,
                timeout=SCRAPE_TIMEOUT,
            )
            if resp.status_code != 200:
                return None
            soup = BeautifulSoup(resp.text, "lxml")
            # ── TODO: extract stream URL ──────────────────────────
            # video_url = soup.select_one("video source").get("src")
            # if not video_url:
            #     return None
            # return StreamSource(
            #     url=video_url,
            #     site_name=self.name,
            #     quality=quality_pref,
            #     is_direct=True,
            #     headers={{"Referer": self.url + "/"}},
            # )
        except requests.RequestException:
            pass
        return None

    # ── Servers ─────────────────────────────────────────────────────
    # def get_servers(self, episode: Episode) -> list[dict]:
    #     \"\"\"Return available servers for server-selection TUI.
    #     Each dict: {{"name": str, "display": str, "link_id": str, "type": str}}
    #     Override this if your provider serves video via multiple servers.
    #     \"\"\"
    #     return []

    # ── Resolve (movies) ────────────────────────────────────────────
    # def resolve(
    #     self, media: MediaResult, audio_pref: str = "sub", quality_pref: str = "best"
    # ) -> Optional[StreamSource]:
    #     \"\"\"Resolve a movie directly (for providers with movie support).
    #     Receive a MediaResult (e.g. from TMDB search) and return a StreamSource.
    #     \"\"\"
    #     return None

    # ── Optional helpers ────────────────────────────────────────────
    def get_supported_qualities(self) -> list[str]:
        return ["best"]

    def get_supported_audio(self) -> list[str]:
        return ["sub"]
'''


def generate_plugin(
    name: str,
    slug: str,
    url: str = "https://example.com",
    category: str = "anime",
) -> str:
    class_name = slug.replace("-", " ").replace("_", " ").title().replace(" ", "")
    return TEMPLATE.format(
        name=name,
        slug=slug.lower().replace(" ", "-"),
        url=url.rstrip("/"),
        category=category,
        class_name=class_name,
    )
